package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeConfigWithCredentials writes a configuration and the credentials file the wizard puts
// beside it, and returns the configuration's path.
func writeConfigWithCredentials(t *testing.T, dir, yaml, creds string) string {
	t.Helper()
	path := filepath.Join(dir, "motita.yaml")
	if err := os.WriteFile(path, []byte(yaml), 0o600); err != nil {
		t.Fatalf("could not write the configuration: %v", err)
	}
	if creds != "" {
		if err := os.WriteFile(CredentialsPath(path), []byte(creds), 0o600); err != nil {
			t.Fatalf("could not write the credentials: %v", err)
		}
	}
	return path
}

func TestCredentialsPathIsBesideTheConfiguration(t *testing.T) {
	if got := CredentialsPath("/home/u/.motita/motita.yaml"); got != "/home/u/.motita/motita.env" {
		t.Fatalf("CredentialsPath = %q", got)
	}
	if got := CredentialsPath("conf"); got != "conf.env" {
		t.Fatalf("CredentialsPath without an extension = %q", got)
	}
}

// The sandbox hides these from the commands it confines: the logins, the home's configuration and
// key file, and the loaded configuration and its key file, made absolute.
func TestSecretFilesNameTheLoginsTheConfigurationAndItsKeys(t *testing.T) {
	t.Setenv("MOTITA_AUTH_DIR", "/auth")
	home := File()
	if got := strings.Join(SecretFiles(""), " "); got != "/auth "+home+" "+CredentialsPath(home) {
		t.Errorf("without a loaded file: %s", got)
	}
	wd, _ := os.Getwd()
	got := SecretFiles("conf/x.yaml")
	if len(got) != 5 || got[3] != filepath.Join(wd, "conf/x.yaml") || got[4] != filepath.Join(wd, "conf/x.env") {
		t.Errorf("a loaded file is made absolute and its key file named: %v", got)
	}
}

// The defect this file exists for: the wizard stored the key in motita.env, and the very next
// load - the first run, in the same process - reported "the LLM key is missing".
func TestLoadReadsTheKeyTheWizardStoredBesideTheFile(t *testing.T) {
	t.Setenv("MOTITA_LLM_API_KEY", "")
	os.Unsetenv("MOTITA_LLM_API_KEY")
	t.Setenv("OPENAI_API_KEY", "")
	os.Unsetenv("OPENAI_API_KEY")
	path := writeConfigWithCredentials(t, t.TempDir(),
		"llm:\n  provider: openai\n  model: gpt-5-mini\n",
		"# Generated by motita config.\nexport MOTITA_LLM_API_KEY='sk-from-the-wizard'\n")

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.LLM.APIKey != "sk-from-the-wizard" {
		t.Fatalf("APIKey = %q, want the stored key", cfg.LLM.APIKey)
	}
}

func TestTheProvidersOwnVariableWinsInTheCredentialsFile(t *testing.T) {
	t.Setenv("OLLAMA_API_KEY", "")
	os.Unsetenv("OLLAMA_API_KEY")
	path := writeConfigWithCredentials(t, t.TempDir(),
		"llm:\n  provider: ollama\n  model: m\n  base_url: https://ollama.com/v1\n",
		"export MOTITA_LLM_API_KEY='generic'\nexport OLLAMA_API_KEY='own'\n")
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.LLM.APIKey != "own" {
		t.Fatalf("APIKey = %q, want the provider's own variable", cfg.LLM.APIKey)
	}
}

// The environment still wins: a key exported in the shell is the user's instruction for this run.
func TestTheEnvironmentWinsOverTheCredentialsFile(t *testing.T) {
	t.Setenv("ANTHROPIC_API_KEY", "from-the-shell")
	path := writeConfigWithCredentials(t, t.TempDir(),
		"llm:\n  provider: anthropic\n  model: m\n",
		"export ANTHROPIC_API_KEY='from-the-file'\n")
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.LLM.APIKey != "from-the-shell" {
		t.Fatalf("APIKey = %q, want the environment", cfg.LLM.APIKey)
	}
}

// A key written in the YAML itself is not replaced by the file beside it.
func TestTheYAMLKeyIsNotReplacedByTheCredentialsFile(t *testing.T) {
	t.Setenv("ANTHROPIC_API_KEY", "")
	os.Unsetenv("ANTHROPIC_API_KEY")
	path := writeConfigWithCredentials(t, t.TempDir(),
		"llm:\n  provider: anthropic\n  model: m\n  api_key: in-the-yaml\n",
		"export ANTHROPIC_API_KEY='from-the-file'\n")
	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.LLM.APIKey != "in-the-yaml" {
		t.Fatalf("APIKey = %q, want the YAML value", cfg.LLM.APIKey)
	}
}

func TestReadCredentialsParsesWhatTheWizardAndAHandEditWrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "c.env")
	body := "# comment\n\n" +
		"export A='it'\\''s'\n" +
		"B=\"dq \\\"x\\\" \\\\ y\"\n" +
		"export C=bare\\ word\n" +
		"D='unterminated\n" +
		"no equals here\n" +
		"=nameless\n" +
		"E=trailing\\\n"
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	got := readCredentials(path)
	want := map[string]string{
		"A": "it's",
		"B": `dq "x" \ y`,
		"C": "bare word",
		"D": "unterminated",
		"E": "trailing",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %q, want %q", k, got[k], v)
		}
	}
	if len(got) != len(want) {
		t.Errorf("parsed %d entries, want %d: %v", len(got), len(want), got)
	}
	if readCredentials(filepath.Join(t.TempDir(), "missing.env")) != nil {
		t.Error("a missing file must read as no credentials")
	}
}

// A provider switch finds the key the wizard stored in the home under the provider's own name -
// and never the generic one, which belongs to the configured provider.
func TestProviderKeyFromEnvFallsBackToTheHomeCredentials(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	for _, v := range []string{"GEMINI_API_KEY", "OPENAI_API_KEY", "MOTITA_LLM_API_KEY"} {
		t.Setenv(v, "")
		os.Unsetenv(v)
	}
	if err := os.MkdirAll(Dir(), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(CredentialsPath(File()), []byte("export GEMINI_API_KEY='g'\nexport MOTITA_LLM_API_KEY='generic'\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if got := ProviderKeyFromEnv("gemini"); got != "g" {
		t.Errorf("gemini = %q, want the stored key", got)
	}
	if got := ProviderKeyFromEnv("openai"); got != "" {
		t.Errorf("openai = %q: the generic variable must not travel to a switch", got)
	}
	t.Setenv("OPENAI_API_KEY", "sk-env")
	if got := ProviderKeyFromEnv("codex"); got != "sk-env" {
		t.Errorf("codex = %q, want OPENAI_API_KEY", got)
	}
	t.Setenv("HOME", "")
	if got := ProviderKeyFromEnv("gemini"); got != "" {
		t.Errorf("with no home there is no stored key, got %q", got)
	}
}

func TestStoredCredentialsReadsTheFileBesideTheConfiguration(t *testing.T) {
	path := writeConfigWithCredentials(t, t.TempDir(), "llm:\n  provider: gemini\n", "export GEMINI_API_KEY='k'\n")
	if got := StoredCredentials(path)["GEMINI_API_KEY"]; got != "k" {
		t.Fatalf("StoredCredentials = %q", got)
	}
}
